var venueHref = [
  {venueName: 'The Garage', venueUrl: 'http://thegarage.london/listings/'},
  {venueName: 'Union Chapel', venueUrl: 'https://store.unionchapel.org.uk/'},
  {venueName: 'Birthdays', venueUrl: 'http://www.birthdaysdalston.com/'},
  {venueName: 'Dublin Castle', venueUrl: 'http://thedublincastle.com/'},
  {venueName: 'Lexington', venueUrl: 'http://thelexington.co.uk/calendar/'},
  {venueName: 'Good Ship', venueUrl: 'https://www.thegoodship.co.uk/'},
  {venueName: 'Shacklewell Arms', venueUrl: 'https://www.shacklewellarms.com/listings'},
  {venueName: 'Windmill', venueUrl: 'https://www.windmillbrixton.co.uk/'},
  {venueName: 'Nambucca', venueUrl: 'http://www.nambucca.co.uk/events/'},
  {venueName: 'Notting Hill Arts Centre', venueUrl: 'https://www.nottinghillartsclub.com/events'},
  {venueName: 'MOTH Club', venueUrl: 'http://www.mothclub.co.uk/events'},
  {venueName: 'Moth Club', venueUrl: 'http://www.mothclub.co.uk/events'},
  {venueName: 'Old Blue Last', venueUrl: 'http://www.theoldbluelast.com/listings/'},
  {venueName: 'Hoxton Square Bar & Kitchen', venueUrl: 'http://www.hoxtonsquarebar.com/events/'},
  {venueName: 'Underworld', venueUrl: 'https://www.theunderworldcamden.co.uk/gigs'},
  {venueName: 'Proud Camden', venueUrl: 'http://proudcamden.com/listings-tickets/'},
  {venueName: 'The Camden Assembly', venueUrl: 'http://camdenassembly.com/whats-on/?range=live-show'},
  {venueName: 'KOKO', venueUrl: 'http://www.koko.uk.com/listings'},
  {venueName: 'Dingwalls', venueUrl: 'http://dingwalls.com/listings/'},
  {venueName: 'Dirty South', venueUrl: 'http://www.ticketmaster.co.uk/'},
  {venueName: 'Amersham Arms', venueUrl: 'https://www.facebook.com/pg/amersham.arms/events/'},
  {venueName: 'Bull & Gate', venueUrl: 'http://www.bullandgatenw5.co.uk/whats-on'},
  {venueName: 'Borderline', venueUrl: 'http://borderline.london/listings/'},
  {venueName: 'Scala', venueUrl: 'http://scala.co.uk/'},
  {venueName: "Old Queens Head", venueUrl: 'http://theoldqueenshead.com/whats-on/'},
  {venueName: 'XOYO', venueUrl: 'http://xoyo.co.uk/whats-on'},
  {venueName: '100 Club', venueUrl: 'http://www.the100club.co.uk/events-calendar/'},
  {venueName: 'Hope & Anchor', venueUrl: 'http://www.hopeandanchor-islington.co.uk/dates-diary'},
  {venueName: 'Cargo', venueUrl: 'http://cargo-london.com/events/'},
  {venueName: 'Servant Jazz Quarters', venueUrl: 'http://servantjazzquarters.com/'},
  {venueName: 'Servants Jazz Quarters', venueUrl: 'http://servantjazzquarters.com/'},
  {venueName: 'St Moritz', venueUrl: 'http://www.stmoritzclub.co.uk/whats-on'},
  {venueName: 'Lock Tavern', venueUrl: 'http://www.lock-tavern.com/event-list/'},
  {venueName: 'Black Heart', venueUrl: 'http://www.ourblackheart.com/'},
  {venueName: 'Purple Turtle', venueUrl: 'http://www.purpleturtlebar.com/camden_holding/index.html'},
  {venueName: 'Victoria', venueUrl: 'http://www.jaguarshoes.com/venues/the-victoria/'},
  {venueName: 'Cafe Oto', venueUrl: 'https://www.cafeoto.co.uk/events/'},
  {venueName: 'The Islington', venueUrl: 'https://www.theislington.com/events/'},
  {venueName: 'Macbeth', venueUrl: 'http://www.themacbeth.co.uk/events/'},
  {venueName: 'The Waiting Room', venueUrl: 'http://waitingroomn16.com/event-list/'},
  {venueName: 'Green Note', venueUrl: 'http://www.greennote.co.uk/events-page/'},
  {venueName: 'Lewis Cubitt Square', venueUrl: 'https://www.kingscross.co.uk/lewis-cubitt-square'},
  {venueName: 'The Finsbury', venueUrl: 'http://www.thefinsbury.co.uk/listings/'},
  {venueName: 'The Sound Lounge', venueUrl: 'http://www.thesoundlounge.org.uk/'},
  {venueName: 'Slaughtered Lamb', venueUrl: 'http://slamb.glasswerk.co.uk/'},
  {venueName: 'Surya', venueUrl: 'http://www.suryalondon.com/events/'},
  {venueName: 'The Troubadour', venueUrl: 'https://www.troubadourlondon.com/'},
  {venueName: 'The Half Moon', venueUrl: 'https://tickets.halfmoon.co.uk/'},
  {venueName: 'Water Rats', venueUrl: 'http://thewaterratsvenue.london/listings.html'},
  {venueName: 'The Pickle Factory', venueUrl: 'https://ovalspace.co.uk/events'},
  {venueName: 'Corsica Studios', venueUrl: 'http://www.corsicastudios.com/whats-on/'},
  {venueName: 'Jazz Cafe', venueUrl: 'http://thejazzcafelondon.com/whats-on'},
  {venueName: 'Kamio', venueUrl: 'http://www.iamkam.io/events'},
  {venueName: 'ECHOES', venueUrl: 'http://archspace.london/'},
  {venueName: 'OMEARA', venueUrl: 'http://www.omearalondon.com/events/'},
  {venueName: 'Omeara', venueUrl: 'http://www.omearalondon.com/events/'},
  {venueName: 'The Dome', venueUrl: 'http://www.dometufnellpark.co.uk/listings/'},
  {venueName: 'Boston Music Room', venueUrl: 'http://www.bostonmusicroom.co.uk/all-listings/'},
  {venueName: 'Mangle E8', venueUrl: 'https://www.manglee8.com/'},
  {venueName: 'Archspace', venueUrl: 'http://archspace.london/'},
  {venueName: 'Arcola Theatre', venueUrl: 'https://www.arcolatheatre.com/events/'},
  {venueName: 'Old Red Lion Theatre', venueUrl: 'http://www.oldredliontheatre.co.uk/shows.html'},
  {venueName: 'Battersea Arts Centre', venueUrl: 'https://www.bac.org.uk/content_category/3262/whats_on/whats_on'},
  {venueName: 'ULU Live at Student Central', venueUrl: 'http://ulu-live.co.uk/'},
  {venueName: 'Hampstead Theatre', venueUrl: 'https://www.hampsteadtheatre.com/whats-on/'}
  // {venueName: 'Lyric Theatre', venueUrl: 'https://www.nimaxtheatres.com/shows/'} // TEST
];

exports.venueHref = venueHref;
